#### 场景
在连续的处理过程中，某次失败需要直接跳过所有的步骤。可以自定义异常类记录步骤中的信息

1. 使用异常
```cpp
try{
	if (!doThings1()){
		throw std::runtime_error("doThings1");
	}

	if (!doThings2()){
		throw std::runtime_error("doThings2");
	}

	if (!doThings3()){
		throw std::runtime_error("doThings3");
	}
} catch (...){

}
```


2. 使用do while
[[do while]]